AWSTemplateFormatVersion: 2010-09-09
Description: My Glue Crawler with a Classifier
Parameters:
  BucketName:
    Type: String
    Default: 'anish-demo-bucket-1121'

  DatabaseName:
    Type: String 
    Default: 'demo-glue-database'

  CrawlerName:
    Type: String 
    Default: 'demo-glue-crawler'

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !GetAtt CrawlerRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${BucketName}'

  CrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              - glue.amazonaws.com
      Description: IAM Role for Crawler
      Policies:
        - PolicyName: CrawlerInlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                  - logs:AssociateKmsKey
                Effect: Allow
                Resource: '*'

              - Action:
                  - 'glue:CreateDatabase'
                  - 'glue:GetDatabase'
                  - 'glue:UpdateDatabase'
                  - 'glue:CreateTable'
                  - 'glue:GetTable'
                  - 'glue:UpdateTable'
                Effect: Allow
                Resource: '*'

              - Action: 's3:GetObject'
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${BucketName}/*'

              - Action:
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::${BucketName}'